title = "Yu Chao (趙佑)"
baseURL = "https://yuchao.page"
theme = "researcher"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]
enableEmoji = true

[params]
  author = "Yu Chao"
  description = "Yu Chao's Resume"
  favicon = "favicon.ico"
  [params.footer]
    text = "Contact Me: chaoyu@link.cuhk.edu.hk"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "https://shinerightstudio.com/"
    weight = 1
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/YuChaoGithub/"
    weight = 2
  [[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/yu-chao-a55b85b2/"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
